spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:todo_management
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # Ajuda se estiver tentando acessar de fora